"""Prepare the 2x2 attack pose sheets of game/assets/attacks/new-characters/ for the game.

For each sheet: the four frames' tight bounds and foot anchors are measured on the transparent PNG, the sheet is saved
as a smaller WebP under game/assets/attacks/poses/, and game/js/poses.js is written (MB.POSES: per character the sheet,
its size and, per frame, x y w h plus the foot point ax, ay). The attack styles in fx.js stand a frame's feet on the
character's floor point and scale frame 0 to the character's height, so frames line up without hand tuning.

Usage:  py tools/pose_sheets.py
"""
import json, os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "game", "assets", "attacks", "new-characters")
OUT = os.path.join(ROOT, "game", "assets", "attacks", "poses")
SCALE = 0.75       # sheets are ~1250 px wide; on the board a character is at most ~400 px tall
THRESHOLD = 24     # alpha below this is stray fringe


def measure(alpha, rect):
    x, y, w, h = rect
    cell = alpha.crop((x, y, x + w, y + h)).point(lambda v: 255 if v >= THRESHOLD else 0)
    bb = cell.getbbox()
    if not bb:
        raise SystemExit(f"empty frame {rect}")
    bx, by, bx2, by2 = bb
    # foot point: the weighted centre of the lowest 22% of the figure (shoes, not a sweeping arm or hair)
    low = cell.crop((bx, by2 - max(4, int((by2 - by) * 0.22)), bx2, by2))
    cols = low.resize((low.width, 1), Image.BOX).tobytes()
    total = sum(cols) or 1
    ax = bx + sum(i * v for i, v in enumerate(cols)) / total
    return {"x": x + bx, "y": y + by, "w": bx2 - bx, "h": by2 - by, "ax": x + ax, "ay": y + by2}


def main():
    os.makedirs(OUT, exist_ok=True)
    inventory = json.load(open(os.path.join(SRC, "sheet-inventory.json"), encoding="utf-8"))
    poses = {}
    for entry in inventory:
        cid = entry["id"]
        im = Image.open(os.path.join(SRC, entry["file"])).convert("RGBA")
        alpha = im.getchannel("A")
        frames = [measure(alpha, f["rect"]) for f in entry["frames"]]
        w, h = round(im.width * SCALE), round(im.height * SCALE)
        im.resize((w, h), Image.LANCZOS).save(os.path.join(OUT, cid + ".webp"), "WEBP", quality=90, method=6, exact=True)
        out = []
        for f in frames:
            out.append({k: round(v * SCALE, 1) if k in ("ax",) else round(v * SCALE) for k, v in f.items()})
        poses[cid] = {"src": f"assets/attacks/poses/{cid}.webp", "w": w, "h": h, "frames": out}
        print(cid, (w, h), [(f["w"], f["h"]) for f in out], f"{os.path.getsize(os.path.join(OUT, cid + '.webp')) // 1024} KB")
    with open(os.path.join(ROOT, "game", "js", "poses.js"), "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/pose_sheets.py: frame bounds and foot anchors of the 2x2 attack pose sheets (assets/attacks/poses/).\n")
        fh.write("window.MB = window.MB || {};\nMB.POSES = " + json.dumps(poses, indent=1) + ";\n")


if __name__ == "__main__":
    main()
