"""Turn the pictures in the Supabase "card-images" bucket into unlockable profile pictures.

For every image there (json files and the common/rare/epic pack art aside) it uploads a 256px square
thumbnail to game-assets/avatars/<id>.webp, uploads the pack art to game-assets/packs/<tier>.webp,
and writes game/js/avatars.js, the list the game unlocks from.

Usage:  SUPABASE_SECRET_KEY=sb_secret_... py tools/sync_avatars.py [--force]
Run it again after adding pictures to card-images; --force also rebuilds thumbnails that already exist.
"""
import io, json, os, re, sys
from PIL import Image
import supabase_storage as sb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_JS = os.path.join(ROOT, "game", "js", "avatars.js")
PACKS = ("common", "rare", "epic")
IMG = re.compile(r"\.(png|jpe?g|webp|gif)$", re.I)
SIZE = 256


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def pretty(stem):
    # "christopher_smith" -> "Christopher Smith", "mr.bandit" -> "Mr. Bandit"
    return " ".join(w[:1].upper() + w[1:] for w in re.split(r"[-_ ]+", stem.replace(".", ". ")) if w)


def webp(im, **kw):
    buf = io.BytesIO()
    im.save(buf, "WEBP", method=5, **kw)
    return buf.getvalue()


def thumb(data):
    im = Image.open(io.BytesIO(data))
    im = im.convert("RGBA" if im.mode in ("RGBA", "LA", "P") else "RGB")
    w, h = im.size
    s = min(w, h)
    # tall pictures keep their upper part, where the face usually is
    top = round((h - s) * 0.2)
    im = im.crop(((w - s) // 2, top, (w - s) // 2 + s, top + s)).resize((SIZE, SIZE), Image.LANCZOS)
    return webp(im, quality=82)


def fingerprint(data):
    # 16x16 grayscale: equal for the same picture saved in another format or quality
    return list(Image.open(io.BytesIO(data)).convert("L").resize((16, 16), Image.BILINEAR).tobytes())


def pack_art(data):
    im = Image.open(io.BytesIO(data)).convert("RGBA")
    w, h = im.size
    return webp(im.resize((360, round(h * 360 / w)), Image.LANCZOS), quality=88)


def main():
    force = "--force" in sys.argv
    sb.ensure_bucket(sb.GAME_BUCKET)
    src = sb.list_objects(sb.CARD_BUCKET)
    have = set(sb.list_objects(sb.GAME_BUCKET, "avatars")) | set(sb.list_objects(sb.GAME_BUCKET, "packs"))

    avatars, seen_ids, prints, items = [], set(), {}, []
    for name in sorted(src):
        if "/" in name or not IMG.search(name):
            continue
        stem = IMG.sub("", name)
        if stem in PACKS:
            path = f"packs/{stem}.webp"
            if force or path not in have:
                items.append((path, pack_art(sb.download(sb.CARD_BUCKET, name))))
            continue
        aid, n = slug(stem), 2
        while aid in seen_ids:  # e.g. clever-kitsune-kirsti.png and clever_kitsune_kirsti.png
            aid, n = f"{slug(stem)}-{n}", n + 1
        path = f"avatars/{aid}.webp"
        built = force or path not in have
        data = thumb(sb.download(sb.CARD_BUCKET, name)) if built else sb.download(sb.GAME_BUCKET, path)
        fp = fingerprint(data)
        twin = next((other for other, f in prints.items() if sum(abs(a - b) for a, b in zip(fp, f)) < len(fp) * 6), None)
        if twin:  # the same picture uploaded twice, maybe as png and jpg
            print(f"skip {name}: same picture as {twin}")
            continue
        prints[name] = fp
        seen_ids.add(aid)
        avatars.append({"id": aid, "name": pretty(stem)})
        if built:
            items.append((path, data))
        print(f"[{len(avatars)}] {'built' if built else 'kept'} {path}", flush=True)

    print(f"{len(avatars)} profile pictures, {len(items)} images to upload")
    failed = sb.upload_many(sb.GAME_BUCKET, items)
    # thumbnails of pictures that were removed or turned out to be duplicates
    stale = sorted(p for p in have if p.startswith("avatars/"))
    stale = [p for p in stale if p not in {f"avatars/{a['id']}.webp" for a in avatars}]
    if stale:
        sb.remove(sb.GAME_BUCKET, stale)
        print("removed " + ", ".join(stale))

    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write("// Unlockable profile pictures. Generated by tools/sync_avatars.py from the card-images bucket;\n"
                "// thumbnails live at game-assets/avatars/<id>.webp. Ids are stored in saves, so never rename one.\n"
                "window.MB = window.MB || {};\n"
                "MB.AVATARS = [\n" + ",\n".join("  " + json.dumps(a, ensure_ascii=False) for a in avatars) + ",\n];\n")
    print(f"wrote {os.path.relpath(OUT_JS, ROOT)}; {len(failed)} uploads failed")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
